### ISSUE TITLE
给模块的ui加特定id？

### ISSUE THREAD

**Issue by HJYblur** [Tencent/LightDiffusionFlow#13]
如题，想要对这个插件的ui部分进行修改时，由于没有特定的id（而是浏览器自带的component-xxx），很难找到对应位置并进行修改。
![ui修改建议](https://github.com/Tencent/LightDiffusionFlow/assets/67328829/2c8603db-c801-4b04-8e5f-a81812ebf3f6)

```[tasklist]
### Tasks
- [ ] Accordion组件增加elem_id
```

**Comment by LegionFu** [comment]
好的，方便说一下具体想做什么样的修改吗？

**Comment by HJYblur** [comment]
比如像下图所示的插件，有对应的id“txt2img_dimensions_row”，可以通过对应id找到相应板块，希望lightdiffusionflow也添加类似的功能。
![image](https://github.com/Tencent/LightDiffusionFlow/assets/67328829/714cde49-f078-40b8-a050-705fc39c13af)

**Comment by LegionFu** [comment]
组件已增加elem_id
