### ISSUE TITLE
Is it possible to have multiple workflows as a single lightflow?

### ISSUE THREAD

**Issue by yasainet** [Tencent/LightDiffusionFlow#21]
How can I make the following example a single lightflow or in some way a lightflow?

1. generate with txt2img
2. generate the generated image with img2img and set Scale:2 in "Resize by".

I usually use the above method when generating images.

The reason I don't use Hires. fix is that I generate about 100 images with txt2img and upscale only the good ones with img2img to avoid waste.

The above is just an example, but how should we use lightflow to deal with the generation method using multiple tabs like txt2img → img2img?

Various advices are welcome!

--

Use comfyUI? This was very difficult for me 😢

**Comment by LegionFu** [comment]
That's an excellent question. However, Lightflow doesn't currently have the capability to automatically trigger another workflow upon the completion of one. (The main challenge lies in implementing user interaction logic.) 

If you're not considering using ComfyUI, you might want to try saving the parameters of both the txt2img and img2img tabs simultaneously. Once you've completed your txt2img workflow, you can then manually switch to the img2img tab to proceed with your next workflow.

I hope this helps you~

**Comment by AlphaMistral** [comment]
We can evaluate a "Batched LightFlow" function which could execute several LightFlows in a sequence with just one click.

**Comment by yasainet** [comment]
> Batched LightFlow

I am very much looking forward to it!
Thank you for all your answers!
