### ISSUE TITLE
添加flow文件之后没有任何反应，不会自动恢复设置，运行生成图片也没有用

### ISSUE THREAD

**Issue by ivanmmz** [Tencent/LightDiffusionFlow#25]
![Snipaste_2023-12-17_18-10-24](https://github.com/Tencent/LightDiffusionFlow/assets/65158038/24bda693-4637-4e86-95a3-2e2716290a5a)

**Comment by LegionFu** [comment]
检查一下控制台，一般都是加载报错了。另外可以刷新一下页面再试试，如果一直是这个情况可以把控制台输出的日志截图发出来。

**Comment by LegionFu** [comment]
对了，如果是使用上遇到了问题可以先检查一下我readme里写的文档，对着看一下FAQ，常见的问题我们都有列出来。另外也可以扫码加一下我们的交流群，一些使用上的问题直接在群里问也是可以的。
