### ISSUE TITLE
和美化插件LOBE冲突导致UI失灵

### ISSUE THREAD

**Issue by LINYANG1991** [Tencent/LightDiffusionFlow#27]
导入FLOW后会导致最上面文生图 图生图等一系列UI失灵  我也在L9BO项目下提交了 ~
提交地址：https://github.com/lobehub/sd-webui-lobe-theme/issues/507#issue-2057343432
@tencent-adm @hzlzh @LegionFu @AlphaMistral

**Comment by AlphaMistral** [comment]
感谢您的反馈. 我们会在元旦假期后开始调查该Issue, 并且创造机会与更多的开源项目 & 开源工作者展开合作. 
顺祝元旦快乐!

**Comment by LegionFu** [comment]
你好，支持LOBE插件的需求，目前优先级暂时会靠后一些。因为我们目前还没有足够的精力来开发这个功能。
不过我们肯定会持续关注这个问题的，同时我们也非常期待能得到各位开源工作者的帮助，一起把插件变得更完善~
