### ISSUE TITLE
export button is sleeping..

### ISSUE THREAD

**Issue by srandovnidobrodruzstvi** [Tencent/LightDiffusionFlow#28]
Hi, could you please advise me how to work with the plugin? 
When I hit export (after generation and selected image), nothing happens. 
Everything is updated.
startup log:

Requirement already satisfied: pip in x:\visions_of_chaos\py\lib\site-packages (23.3.2)
venv "X:\Visions_of_Chaos\MLF\Text To Image\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Launching Web UI with arguments: --share --no-half-vae --xformers --autolaunch
Style database not found: X:\Visions_of_Chaos\MLF\Text To Image\stable-diffusion-webui\styles.csv
X:/Visions_of_Chaos/MLF/Text To Image/stable-diffusion-webui/models/LightDiffusionFlow
[-] ADetailer initialized. version: 23.11.1, num models: 9
ControlNet preprocessor location: X:\Visions_of_Chaos\MLF\Text To Image\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-12-31 11:28:49,962 - ControlNet - [0;32mINFO[0m - ControlNet v1.1.423
2023-12-31 11:28:50,049 - ControlNet - [0;32mINFO[0m - ControlNet v1.1.423
sd-webui-prompt-all-in-one background API service started successfully.
Loading weights [a21c9949ef] from X:\Visions_of_Chaos\MLF\Text To Image\stable-diffusion-webui\models\Stable-diffusion\_SDXL_1_0\thinkdiffusionxl_v10.safetensors
LightDiffusionFlow ç»‘ĺ®šĺ®Ść
Creating model from config: X:\Visions_of_Chaos\MLF\Text To Image\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Running on local URL:  http://127.0.0.1:7860
Applying attention optimization: xformers... done.
Model loaded in 6.6s (load weights from disk: 1.4s, create model: 0.9s, apply weights to model: 2.4s, apply dtype to VAE: 0.9s, move model to device: 0.1s, calculate empty prompt: 0.9s).

----------------- light_diffusion_flow api start------------------
Startup time: 25.0s (prepare environment: 5.0s, import torch: 2.1s, import gradio: 0.7s, setup paths: 0.6s, initialize shared: 0.2s, other imports: 0.5s, load scripts: 2.8s, create ui: 1.9s, gradio launch: 11.0s).

Thank you!

**Comment by LegionFu** [comment]
Any screenshot? Might be startup failure, although there are no relevant errors indicated in the log, errors may occur on the web side. Refresh the webpage and try again?

**Comment by srandovnidobrodruzstvi** [comment]
ok i already know is the problem. there is a collision with this plugin: https://github.com/ilian6806/stable-diffusion-webui-state . without it your extension works fine. So thank you a have a nice day

**Comment by LegionFu** [comment]
have a nice day~
