### ISSUE TITLE
可以发布一个直接输入图片，获得图片参数的版本吗，即不继承到webui上

### ISSUE THREAD

**Issue by Nomination-NRB** [Tencent/LightDiffusionFlow#29]

**Comment by LegionFu** [comment]
如果是需要获取图片内的保存的参数，可以直接使用官方的PNG Info功能就行？
我们的插件现在是支持解析部分PNG Info的数据，然后自动还原到面板上。

**Comment by Nomination-NRB** [comment]
> 如果是需要获取图片内的保存的参数，可以直接使用官方的PNG Info功能就行？ 我们的插件现在是支持解析部分PNG Info的数据，然后自动还原到面板上。

官方的png info给出的参数不完整，我以为这个repo是重构了它的png info
