### ISSUE TITLE
能否增加一个导出路径的配置项？

### ISSUE THREAD

**Issue by huoxiongmao** [Tencent/LightDiffusionFlow#3]
目前导出时，默认是在下载文件夹，可否增加一个设置，可以自由设置保存路径。

**Comment by LegionFu** [comment]
相关的功能目前有规划，但是还没确定最终的交互形式，后续肯定会有的。

**Comment by LegionFu** [comment]
你好，可以试试我们的最新版本~ 
虽然导出仍然是调用的浏览器的下载功能，但是我们新增加了保存flow的功能，现在可以直接保存到指定文件夹了，保存好的flow支持下拉框选择并加载。另外可以直接在设置页面修改保存flow的路径。
