### ISSUE TITLE
支持这个项目！反馈一些使用感受。

### ISSUE THREAD

**Issue by Liuyingzhou** [Tencent/LightDiffusionFlow#31]
首先感谢大佬。
每次都要配参数是很多人换Comfyui的原因，这个项目正式解决之道，非常棒。

几点反馈：
1、跟stable-diffusion-webui-state有冲突，不能并存
2、当调整很多参数以后，保存下来的文件中可以看出同一个参数反复出现很多条，并且值都不一样
3、还有很多参数没有记录，比如ultimate upscale，和img2img的batch处理等等

祝项目原来越好！

**Comment by LegionFu** [comment]
嗯嗯，谢谢支持啦~
对于你提出的几个问题我简单回答一下：
1. 冲突是因为我们的项目最开始就是基于sd webui state这个插件做的拓展，所以部分逻辑是有重合的。解决冲突可能需要花不少的时间，我们目前可能没太多精力来做这些事。（这个问题处理优先级可能会比较低）
2. 同一个参数反复出现很多条的问题，如果是指：某个值既存了“model”又存了“models”和“checkpoint”这种情况的话，可以理解成我们开发过程中为了兼容中文版本的一种trick。因为页面切换成中文后，读取某些选项的命名也变成了中文，但是一个中文词经常对应会有多种英文翻译（比如：模型对应可以是model、models、checkpoint等英文词翻译过来的结果），所以为了避免一些常见选项出现保存错误的问题才有了这种操作。😢
3. 还有很多参数面板确实目前还没有支持，比如下方 Scripts以下的面板，这块暂时也是因为情况比较复杂所以暂时还没有加上，等后续我们稍微空闲一点会马上安排~
