### ISSUE TITLE
大佬我想问一下我为什么打不开社区呀

### ISSUE THREAD

**Issue by jinitaimei11111** [Tencent/LightDiffusionFlow#32]
![微信图片_20240307213828](https://github.com/Tencent/LightDiffusionFlow/assets/162590843/59cd86f5-39be-4641-b203-eee0ba880815)
打开开源社区后所有的图都是无法显示的 ，并且所有的模型都无法下载

**Comment by LegionFu** [comment]
啊，这两天服务器有点问题还在修复中，再等等~

**Comment by jinitaimei11111** [comment]
非常感谢~辛苦辛苦

**Comment by AlphaMistral** [comment]
Resolved.
