### ISSUE TITLE
【建议】能否增加一个直接传递参数的 API

### ISSUE THREAD

**Issue by jianwu003** [Tencent/LightDiffusionFlow#34]
亲爱的作者，能否增加一个直接传递 flow 文件里面的参数，然后返回解析后的 sd 参数的 API，因为我有一种自动化的需求需要用到 flow 文件，但是目前的 read_file API 只能通过点击上传文件后才能识别此文件

**Comment by LegionFu** [comment]
我们这些参数就是直接读取完就设置到对应组件上的，参数名对应就是组件名，没有其他处理步骤。你如果是希望通过api批量调用sd出图可能需要自己生成相关api的参数才行，我们的插件目前没有开发api批量调用相关的逻辑。
