### ISSUE TITLE
导入工作流文件后，ControlNet预处理器和模型一直处于加载中，请问应该如何解决?

### ISSUE THREAD

**Issue by leezhao415** [Tencent/LightDiffusionFlow#6]

**Comment by leezhao415** [comment]
环境：秋叶整合包4.3，WebUI1.6.0
云端页面汉化未启用
插件加载状态：
Start parsing settings...
importing image: 'txt2img_controlnet_ControlNet-0_input_image'
importing image: 'txt2img_controlnet_ControlNet-1_input_image'
importing image: 'txt2img_controlnet_ControlNet-2_input_image'
import completed!

**Comment by LegionFu** [comment]
有使用sd-webui-prompt-all-in-one插件吗？暂时先关闭再重新导入试一下？
目前加载参数可能会有些不稳定的情况，如果一直显示加载中，可以临时关闭一下我说的这个插件再试试，或者刷新浏览器多试几次载入。如果还是不行的话，就耐心等待我们后续的优化更新吧～

**Comment by leezhao415** [comment]
ok👌
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月23日 21:22 |
| 收件人 | Tencent/LightDiffusionFlow ***@***.***> |
| 抄送人 | leezhao ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [Tencent/LightDiffusionFlow] 导入工作流文件后，ControlNet预处理器和模型一直处于加载中，请问应该如何解决? (Issue #6) |

有使用sd-webui-prompt-all-in-one插件吗？暂时先关闭再重新导入试一下？
目前加载参数可能会有些不稳定的情况，如果一直显示加载中，可以临时关闭一下我说的这个插件再试试，或者刷新浏览器多试几次载入。如果还是不行的话，就耐心等待我们后续的优化更新吧～

**Comment by LegionFu** [comment]
可以尝试我们最新的版本v2.1.3，在设置里增加了Core模型，就是只支持txt2img和img2img的基本参数以及ControlNet参数的模式。出现无限加载的概率应该会很小了。
