### ISSUE TITLE
能否增加一个本地保存功能

### ISSUE THREAD

**Issue by Tairraos** [Tencent/LightDiffusionFlow#8]
我看导出的flow只有几百个字节，只是自己保存工作流，文件到处塞麻烦，不如再加个写indexeddb或者localStorage的功能。
需要自己保存自己的方案，只需要存本地。
需要分享的时候再导出成文件，这样用起来更爽。

**Comment by AlphaMistral** [comment]
感谢您的建议, 我们会充分评估.

**Comment by LegionFu** [comment]
现在最新版本已经支持咯，可以更新一下试试。
